"""
templates.py — Legal text, disclaimers, and product description templates
for the Ravinala PDF reporting engine.
"""
from typing import Optional


class ReportingTemplates:
    """
    Standard text blocks reused across all report types.
    All methods are static and return plain strings.
    """

    # ─────────────────────────────────────────────────────────────
    # DISCLAIMERS
    # ─────────────────────────────────────────────────────────────

    @staticmethod
    def disclaimer_full() -> str:
        return (
            "IMPORTANT DISCLAIMER\n\n"
            "This document has been produced by Ravinala for informational and illustrative "
            "purposes only. It does not constitute an offer, invitation, or recommendation "
            "to enter into any transaction or to buy or sell any financial instrument.\n\n"
            "All pricing, analytics, and risk metrics presented herein are based on "
            "mathematical models and market data that are subject to assumptions, limitations, "
            "and potential inaccuracies. Actual market prices may differ materially from "
            "indicative prices shown. The scenarios presented are hypothetical and do not "
            "represent a guarantee or prediction of future outcomes.\n\n"
            "Structured products involve complex risks including, but not limited to: market "
            "risk, credit risk, liquidity risk, and the risk of total or partial loss of "
            "invested capital. Investors should carefully consider whether such products are "
            "appropriate for their investment objectives, financial situation, and risk "
            "tolerance before investing.\n\n"
            "Past performance is not indicative of future results. The value of investments "
            "and the income from them may go down as well as up.\n\n"
            "This document is confidential and intended solely for the use of the designated "
            "recipient. Any unauthorized reproduction, distribution, or disclosure is strictly "
            "prohibited. For professional investors only. Not suitable for retail distribution.\n\n"
            "Generated by Ravinala v2.0 — \u00a9 2026 TSIVAHINY Matthias"
        )

    @staticmethod
    def disclaimer_short() -> str:
        return (
            "For internal use only. Pricing is indicative. Not for distribution. "
            "Ravinala v2.0 \u00a9 2026 TSIVAHINY Matthias."
        )

    @staticmethod
    def risk_warning_structured_products() -> str:
        return (
            "RISK WARNING — STRUCTURED PRODUCTS: Structured products involve complex risks "
            "including market risk, credit risk, liquidity risk, and potential loss of capital. "
            "These instruments are not suitable for all investors. The complexity of these "
            "products means that investors may not fully understand all of the risks involved. "
            "Please refer to the full risk disclosure document before investing."
        )

    @staticmethod
    def risk_warning_capital_at_risk() -> str:
        return (
            "CAPITAL AT RISK WARNING: This product does not provide full capital protection. "
            "Investors may lose some or all of their invested capital if the underlying "
            "asset falls below the barrier level at the final observation date. "
            "The maximum loss is limited to 100% of the invested notional."
        )

    @staticmethod
    def risk_warning_barrier_products() -> str:
        return (
            "BARRIER RISK WARNING: This product contains knock-in barrier features. "
            "If the underlying asset trades at or below the knock-in barrier level "
            "during the observation period (continuous) or at the final observation date "
            "(discrete), the capital protection is removed and the investor is exposed "
            "to the full downside performance of the underlying asset. "
            "The barrier event may occur at any time and without prior notice."
        )

    @staticmethod
    def model_limitations() -> str:
        return (
            "MODEL LIMITATIONS: The pricing model (Monte Carlo simulation and/or "
            "Black-Scholes framework) relies on simplifying assumptions including "
            "log-normal price distribution, constant or deterministic volatility, "
            "continuous trading, and frictionless markets. These assumptions may not "
            "hold under actual market conditions, particularly during periods of market "
            "stress. Model risk — the risk that the model does not accurately capture "
            "the behavior of the underlying — should be considered when interpreting "
            "these results. Greeks and sensitivity measures are computed numerically "
            "and subject to discretization error."
        )

    @staticmethod
    def contact_block() -> str:
        return (
            "For more information, please contact:\n"
            "Ravinala Structuring Desk\n"
            "Email: structuring@ravinala.com\n"
            "Ravinala v2.0 \u00a9 2026 TSIVAHINY Matthias"
        )

    # ─────────────────────────────────────────────────────────────
    # PRODUCT DESCRIPTION TEMPLATES
    # ─────────────────────────────────────────────────────────────

    @staticmethod
    def product_description_template(product_type: str) -> str:
        """
        Returns a description template string with {placeholder} variables
        for the given product type.
        """
        templates = {
            'autocall': (
                "This is a {tenor}-year Autocallable Note linked to {underlyings}. "
                "On each {frequency} observation date, if the underlying closes at or "
                "above {autocall_barrier}% of its initial level ({autocall_abs}), the "
                "note is automatically redeemed at par (100% of notional) plus a coupon "
                "of {coupon_rate}% per annum{memory_clause}. "
                "If not autocalled, a conditional coupon of {coupon_rate}% is paid "
                "if the underlying is above the coupon barrier of {coupon_barrier}%"
                "{memory_clause}. "
                "At final maturity, if the underlying has never closed below the "
                "knock-in barrier of {ki_barrier}%, the investor receives 100% of "
                "notional. If the knock-in barrier has been breached, the investor "
                "receives the notional multiplied by the final performance of the "
                "underlying (capital at risk, maximum loss = 100%)."
            ),
            'phoenix': (
                "This is a {tenor}-year Phoenix Autocallable Note linked to {underlyings}. "
                "On each {frequency} observation date, the note may be automatically "
                "called if the underlying closes at or above {autocall_barrier}% of "
                "its initial level, paying par plus accrued coupons. A conditional "
                "coupon of {coupon_rate}% is paid independently on each observation "
                "date if the underlying is above {coupon_barrier}%{memory_clause}. "
                "At maturity, the redemption is linked to underlying performance "
                "relative to the knock-in barrier of {ki_barrier}%."
            ),
            'athena': (
                "This is a {tenor}-year Athena Autocallable Note linked to {underlyings}. "
                "The structure features annual autocall observations at {autocall_barrier}% "
                "of initial level. If called, the investor receives par plus all "
                "accumulated coupons at {coupon_rate}% per annum (with memory effect). "
                "At maturity, capital protection applies if the underlying is above "
                "{ki_barrier}%; otherwise the investor participates in the downside."
            ),
            'vanilla_call': (
                "This is a European-style call option on {underlyings} with a strike "
                "price of {strike_pct}% of the initial spot ({strike_abs}) and a "
                "maturity of {tenor} years. The holder has the right, but not the "
                "obligation, to receive the positive performance of the underlying "
                "above the strike price at expiry. The option premium is paid upfront "
                "and is the maximum loss for the buyer."
            ),
            'vanilla_put': (
                "This is a European-style put option on {underlyings} with a strike "
                "price of {strike_pct}% of the initial spot ({strike_abs}) and a "
                "maturity of {tenor} years. The holder has the right, but not the "
                "obligation, to receive the positive performance of the put payoff "
                "(strike minus spot, floored at zero) at expiry. "
                "The option premium is paid upfront and is the maximum loss for the buyer."
            ),
            'european_digital': (
                "This is a European digital (binary) option on {underlyings} with a "
                "trigger level of {strike_pct}% ({strike_abs}) and a maturity of "
                "{tenor} years. At expiry, the option pays a fixed amount if the "
                "underlying closes above (call) or below (put) the trigger level, "
                "and zero otherwise."
            ),
            'barrier_option': (
                "This is a barrier option on {underlyings} with a strike of {strike_pct}% "
                "({strike_abs}) and a barrier level of {barrier_pct}%, maturing in "
                "{tenor} years. The option activates (knock-in) or deactivates "
                "(knock-out) depending on whether the underlying trades through the "
                "barrier level during the option life."
            ),
            'reverse_convertible': (
                "This is a {tenor}-year Reverse Convertible Note linked to {underlyings}. "
                "The investor receives a fixed coupon of {coupon_rate}% per annum, "
                "paid {frequency}. At maturity, if the underlying closes above "
                "{barrier_pct}% of its initial level, the investor receives 100% of "
                "notional. If the underlying closes below this level, the investor "
                "receives the notional multiplied by the final performance of the "
                "underlying (capital at risk). The coupon provides a buffer against "
                "moderate declines in the underlying."
            ),
            'capital_protected_note': (
                "This is a {tenor}-year Capital Protected Note linked to {underlyings}. "
                "The note provides {protection}% capital protection at maturity — "
                "the investor is guaranteed to receive at least {protection}% of the "
                "initial notional regardless of market performance. "
                "In addition, the investor participates in {participation}% of the "
                "upside performance of the underlying above 100%{cap_clause}. "
                "This structure is suitable for investors seeking equity market exposure "
                "with downside protection."
            ),
            'worst_of_basket': (
                "This is a {tenor}-year Worst-of Basket product linked to a basket of "
                "{n_underlyings} assets ({underlyings}). The payoff at maturity is "
                "determined by the worst-performing asset in the basket. "
                "Autocall/coupon barriers are typically observed on the worst performer, "
                "offering enhanced yield in exchange for worst-of risk."
            ),
            'best_of_basket': (
                "This is a {tenor}-year Best-of Basket product linked to a basket of "
                "{n_underlyings} assets ({underlyings}). The payoff is linked to the "
                "best-performing asset in the basket at maturity, providing upside "
                "exposure to the strongest performer."
            ),
            'himalaya': (
                "This is a {tenor}-year Himalaya option linked to a basket of "
                "{n_underlyings} assets. At each annual observation date, the "
                "best-performing asset is removed from the basket and its return "
                "is locked in. At maturity, the final payoff is the average of "
                "all locked-in returns, providing diversified exposure to peak "
                "performers across the basket."
            ),
            'cliquet': (
                "This is a {tenor}-year Cliquet (Ratchet) option on {underlyings}. "
                "Returns are measured over successive {frequency} sub-periods. "
                "Each periodic return is floored and/or capped, and the total payoff "
                "is the sum of these clipped returns. This structure monetizes "
                "realized volatility while limiting extreme outcomes."
            ),
            'variance_swap': (
                "This is a {tenor}-year Variance Swap on {underlyings}. "
                "The payoff is based on the difference between the realized variance "
                "of the underlying over the tenor and the strike variance of "
                "{strike_pct}% (annualized vol\u00b2). "
                "The notional is expressed in variance notional (vega notional / "
                "2 \u00d7 strike vol). Variance swaps provide pure exposure to "
                "realized volatility without delta hedging."
            ),
            'range_accrual': (
                "This is a {tenor}-year Range Accrual note on {underlyings}. "
                "A coupon of {coupon_rate}% per annum accrues on a daily basis "
                "for each day the underlying trades within a specified range. "
                "The proportion of in-range days determines the effective coupon, "
                "providing enhanced yield in stable market conditions."
            ),
            'convertible_bond': (
                "This is a {tenor}-year Convertible Bond linked to {underlyings}. "
                "The bond pays a fixed coupon of {coupon_rate}% per annum and "
                "provides the holder with the right to convert into shares at a "
                "conversion price of {strike_abs}. The instrument combines "
                "fixed-income downside protection with equity upside participation."
            ),
            'credit_linked_note': (
                "This is a {tenor}-year Credit Linked Note (CLN). "
                "The note pays {coupon_rate}% per annum and provides the issuer "
                "with credit protection on a reference entity. In the event of a "
                "credit event (default, restructuring, failure to pay), the note "
                "is redeemed at the recovery value rather than par. "
                "Investors are exposed to both interest rate risk and the credit "
                "risk of the reference entity."
            ),
            'custom': (
                "This is a bespoke structured product designed to meet specific "
                "investment objectives. Please refer to the full term sheet for "
                "detailed terms and conditions. All terms are indicative and subject "
                "to final confirmation."
            ),
        }
        return templates.get(product_type, templates['custom'])

    @staticmethod
    def generate_product_description(trade: dict) -> str:
        """
        Fill in the template for the trade's product_type with actual values.
        Handles missing values gracefully with 'N/A'.
        """
        pt = trade.get('product_type', 'custom')
        template = ReportingTemplates.product_description_template(pt)

        # Collect underlying names
        uls = trade.get('underlyings', [])
        underlying_names = ', '.join(
            u.get('ticker', u.get('name', 'N/A')) for u in uls
        ) if uls else 'N/A'
        n_underlyings = len(uls) if uls else 1
        first_ul = uls[0] if uls else {}
        spot_at_inception = first_ul.get('spot_at_inception', 0) or 0

        # Extract barriers
        barriers = trade.get('barriers', []) or []
        ki_barrier = next((b.get('level_pct', 'N/A') for b in barriers
                           if b.get('barrier_type') in ('knock_in',)), 'N/A')
        autocall_barrier = next((b.get('level_pct', 100) for b in barriers
                                 if b.get('barrier_type') == 'autocall'), 100)
        coupon_barrier_pct = next((b.get('level_pct', 'N/A') for b in barriers
                                   if b.get('barrier_type') == 'coupon'), 'N/A')
        barrier_pct = barriers[0].get('level_pct', 'N/A') if barriers else 'N/A'

        # Autocall abs level
        autocall_abs = 'N/A'
        if autocall_barrier != 'N/A' and spot_at_inception:
            try:
                autocall_abs = f'{spot_at_inception * float(autocall_barrier) / 100:,.2f}'
            except Exception:
                pass

        # Coupon
        coupon = trade.get('coupon') or {}
        coupon_rate = coupon.get('rate_pct', 'N/A')
        frequency = coupon.get('frequency', 'annual')
        is_memory = coupon.get('is_memory', False)
        memory_clause = ' (with memory effect — previously unpaid coupons are paid retroactively)' if is_memory else ''

        # Strike
        strike_pct = trade.get('strike_pct', 100) or 100
        strike_abs_val = trade.get('strike_abs')
        if strike_abs_val is None and spot_at_inception:
            try:
                strike_abs_val = spot_at_inception * float(strike_pct) / 100
            except Exception:
                pass
        strike_abs = f'{strike_abs_val:,.2f}' if isinstance(strike_abs_val, (int, float)) else 'N/A'

        # Tenor
        tenor = trade.get('tenor_years', 1) or 1

        # Capital protection
        protection = trade.get('capital_protection_pct', 100) or 100
        participation = trade.get('participation_rate', 100) or 100
        cap_pct = trade.get('cap_pct')
        cap_clause = f', capped at {cap_pct}%' if cap_pct else ''

        values = {
            'tenor': f'{tenor:.0f}' if float(tenor) == int(float(tenor)) else f'{tenor:.1f}',
            'underlyings': underlying_names,
            'n_underlyings': n_underlyings,
            'frequency': frequency,
            'autocall_barrier': autocall_barrier,
            'autocall_abs': autocall_abs,
            'coupon_rate': coupon_rate,
            'coupon_barrier': coupon_barrier_pct,
            'ki_barrier': ki_barrier,
            'ki_text': 'knock-in barrier has been breached and the ' if ki_barrier != 'N/A' else '',
            'above_below': 'above' if ki_barrier == 'N/A' else 'at or above',
            'ki_risk_clause': (
                f'If the {ki_barrier}% knock-in barrier is breached, '
                'the capital is at risk and the investor participates fully in the downside.'
            ) if ki_barrier != 'N/A' else '',
            'memory_clause': memory_clause,
            'strike_pct': strike_pct,
            'strike_abs': strike_abs,
            'barrier_pct': barrier_pct,
            'protection': protection,
            'participation': participation,
            'cap_clause': cap_clause,
        }

        try:
            return template.format(**values)
        except (KeyError, ValueError):
            return template  # return raw template if substitution fails

    # ─────────────────────────────────────────────────────────────
    # SCENARIO HELPERS
    # ─────────────────────────────────────────────────────────────

    @staticmethod
    def scenario_descriptions() -> dict:
        return {
            'Strong Rally':  'Underlying appreciates significantly above autocall trigger — early redemption likely',
            'Mild Bull':     'Moderate positive performance — coupons paid, potential mid-tenor autocall',
            'Flat':          'Underlying near initial level at all observations',
            'Mild Bear':     'Moderate decline, above knock-in barrier — coupons potentially missed',
            'Bear':          'Significant decline approaching or breaching the knock-in barrier',
            'Stress / Crash':'Severe decline well below knock-in — full capital at risk',
        }

    @staticmethod
    def mifid_notice() -> str:
        return (
            "MiFID II / MiFIR Notice: This communication is directed at eligible "
            "counterparties and professional clients only. It is not intended for "
            "retail investors. The product described herein may not be appropriate "
            "for all investors and investors should seek independent financial advice "
            "if in any doubt."
        )
