"""Macro Export Module — Ravinala v2.0
Excel export + Email for Global Macro Terminal.
"""
from __future__ import annotations

import io
import smtplib
import os
from datetime import datetime, timezone
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

import pandas as pd

try:
    import openpyxl
    from openpyxl.styles import (Alignment, Font, PatternFill, Border, Side,
                                  numbers as xlnumbers)
    from openpyxl.utils import get_column_letter
    _XL_OK = True
except ImportError:
    _XL_OK = False


# ─────────────────────────────────────────────────────────────────
# EXCEL EXPORTER
# ─────────────────────────────────────────────────────────────────

class MacroExcelExporter:
    """Generate a Bloomberg-style Excel snapshot of global macro data."""

    # Colour palette
    _HDR_FILL  = "1B2838"
    _ALT_FILL  = "1A2035"
    _BG_FILL   = "0E1117"
    _POS_FONT  = "00C853"
    _NEG_FONT  = "FF1744"
    _HDR_FONT  = "FFFFFF"
    _DATA_FONT = "E6EDF3"
    _ACC_FONT  = "00D9A6"

    def _wb_styles(self):
        """Return style helpers dict."""
        return {
            'hdr_font':  Font(bold=True, color=self._HDR_FONT, size=10, name='Calibri'),
            'data_font': Font(color=self._DATA_FONT, size=9, name='Calibri'),
            'pos_font':  Font(color=self._POS_FONT, size=9, name='Calibri', bold=True),
            'neg_font':  Font(color=self._NEG_FONT, size=9, name='Calibri', bold=True),
            'title_font':Font(bold=True, color=self._ACC_FONT, size=12, name='Calibri'),
            'hdr_fill':  PatternFill("solid", fgColor=self._HDR_FILL),
            'alt_fill':  PatternFill("solid", fgColor=self._ALT_FILL),
            'bg_fill':   PatternFill("solid", fgColor=self._BG_FILL),
            'thin_border': Border(
                bottom=Side(style='thin', color='30363D'),
            ),
            'center': Alignment(horizontal='center', vertical='center'),
            'right':  Alignment(horizontal='right',  vertical='center'),
            'left':   Alignment(horizontal='left',   vertical='center'),
        }

    def _write_header(self, ws, cols: list, s: dict):
        """Write styled header row."""
        for ci, col_name in enumerate(cols, 1):
            cell = ws.cell(row=1, column=ci, value=col_name)
            cell.font = s['hdr_font']
            cell.fill = s['hdr_fill']
            cell.alignment = s['center']

    def _write_data_row(self, ws, row_idx: int, values: list, s: dict,
                         chg_cols: list = None):
        fill = s['alt_fill'] if row_idx % 2 == 0 else s['bg_fill']
        for ci, val in enumerate(values, 1):
            cell = ws.cell(row=row_idx + 1, column=ci, value=val)
            cell.fill = fill
            cell.border = s['thin_border']
            if chg_cols and ci in chg_cols and isinstance(val, (int, float)):
                cell.font = s['pos_font'] if val >= 0 else s['neg_font']
            else:
                cell.font = s['data_font']
                cell.alignment = s['right'] if isinstance(val, (int, float)) else s['left']

    def _autofit(self, ws, min_w: int = 8, max_w: int = 40):
        for col in ws.columns:
            mx = max((len(str(c.value)) for c in col if c.value), default=min_w)
            ws.column_dimensions[get_column_letter(col[0].column)].width = min(max(mx + 2, min_w), max_w)

    def _add_title(self, ws, title: str, ts: str, s: dict):
        ws.sheet_view.showGridLines = False
        ws.cell(1, 1).value = title
        ws.cell(1, 1).font = s['title_font']
        ws.cell(2, 1).value = f"Generated by Ravinala v2.0 — {ts}"
        ws.cell(2, 1).font = Font(color="5B7FA6", size=8, italic=True)
        return 4  # data starts at row 4

    def _sheet_df(self, wb, title: str, df: pd.DataFrame, ts: str,
                   chg_col_names: list = None):
        """Add a DataFrame sheet with full styling."""
        if not _XL_OK or df is None or df.empty:
            return
        s   = self._wb_styles()
        ws  = wb.create_sheet(title=title[:31])
        off = self._add_title(ws, title, ts, s)
        cols = [c for c in df.columns if c not in ('sparkline',)]
        chg_indices = [i+1 for i, c in enumerate(cols) if c in (chg_col_names or [])]
        ws.freeze_panes = ws.cell(off + 1, 1)
        for ci, col in enumerate(cols, 1):
            cell = ws.cell(row=off, column=ci, value=col)
            cell.font = s['hdr_font']
            cell.fill = s['hdr_fill']
            cell.alignment = s['center']
        for ri, row in enumerate(df[cols].itertuples(index=False), 1):
            vals = list(row)
            fill = s['alt_fill'] if ri % 2 == 0 else s['bg_fill']
            for ci, val in enumerate(vals, 1):
                cell = ws.cell(row=off + ri, column=ci, value=val)
                cell.fill = fill
                cell.border = s['thin_border']
                if ci in chg_indices and isinstance(val, (int, float)):
                    cell.font = s['pos_font'] if val >= 0 else s['neg_font']
                else:
                    cell.font = s['data_font']
                    cell.alignment = s['right'] if isinstance(val, (int, float)) else s['left']
        self._autofit(ws)

    @staticmethod
    def _utc_timestamp(value: object | None = None) -> datetime:
        """Normalize optional timestamp inputs to timezone-aware UTC datetimes."""
        if value is None:
            return datetime.now(timezone.utc)
        if isinstance(value, datetime):
            return value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)
        return datetime.now(timezone.utc)

    def export_bytes(self, data: dict) -> bytes:
        """Generate Excel workbook and return as bytes."""
        if not _XL_OK:
            raise ImportError("openpyxl is required for Excel export.")
        from openpyxl import Workbook
        wb = Workbook()
        wb.remove(wb.active)  # remove default sheet
        ts = self._utc_timestamp(data.get('timestamp')).strftime('%Y-%m-%d %H:%M UTC')
        s  = self._wb_styles()

        # ── Dashboard summary sheet ──────────────────────────────
        ws_dash = wb.create_sheet("Dashboard")
        ws_dash.sheet_view.showGridLines = False
        ws_dash.cell(1, 1).value = "RAVINALA — Global Macro Snapshot"
        ws_dash.cell(1, 1).font = Font(bold=True, color="00D9A6", size=14)
        ws_dash.cell(2, 1).value = ts
        ws_dash.cell(2, 1).font = Font(color="5B7FA6", size=9, italic=True)

        row = 4
        sections = [
            ("Equity Indices", data.get('indices', pd.DataFrame()),
             ['name', 'flag', 'group', 'last', 'change_pct', 'ytd_pct'],
             ['change_pct', 'ytd_pct']),
            ("FX Rates", data.get('fx', pd.DataFrame()),
             ['name', 'flag', 'group', 'last', 'change_pct'],
             ['change_pct']),
            ("Commodities", data.get('commodities', pd.DataFrame()),
             ['name', 'flag', 'group', 'last', 'change_pct'],
             ['change_pct']),
        ]
        for sec_title, df, show_cols, chg_cols_n in sections:
            if df is None or df.empty: continue
            avail = [c for c in show_cols if c in df.columns]
            ws_dash.cell(row, 1).value = sec_title.upper()
            ws_dash.cell(row, 1).font = Font(bold=True, color="00D9A6", size=10)
            row += 1
            for ci, col in enumerate(avail, 1):
                cell = ws_dash.cell(row, ci, col)
                cell.font = s['hdr_font']; cell.fill = s['hdr_fill']
            row += 1
            chg_idx = [i+1 for i, c in enumerate(avail) if c in chg_cols_n]
            for ri, (_, dr) in enumerate(df[avail].iterrows()):
                fill = s['alt_fill'] if ri % 2 == 0 else s['bg_fill']
                for ci, val in enumerate(dr.tolist(), 1):
                    cell = ws_dash.cell(row, ci, val)
                    cell.fill = fill; cell.border = s['thin_border']
                    if ci in chg_idx and isinstance(val, (int, float)):
                        cell.font = s['pos_font'] if val >= 0 else s['neg_font']
                    else:
                        cell.font = s['data_font']
                row += 1
            row += 1
        self._autofit(ws_dash)

        # ── Individual sheets ────────────────────────────────────
        idx = data.get('indices', pd.DataFrame())
        if not (idx is None or (isinstance(idx, pd.DataFrame) and idx.empty)):
            self._sheet_df(wb, "Equity Indices", idx, ts, ['change_pct', 'ytd_pct'])

        bonds = data.get('bonds', pd.DataFrame())
        if not (bonds is None or (isinstance(bonds, pd.DataFrame) and bonds.empty)):
            self._sheet_df(wb, "Fixed Income", bonds, ts, ['chg_bps', 'spread_vs_us'])

        fx = data.get('fx', pd.DataFrame())
        if not (fx is None or (isinstance(fx, pd.DataFrame) and fx.empty)):
            self._sheet_df(wb, "FX", fx, ts, ['change_pct'])

        comm = data.get('commodities', pd.DataFrame())
        if not (comm is None or (isinstance(comm, pd.DataFrame) and comm.empty)):
            self._sheet_df(wb, "Commodities", comm, ts, ['change_pct'])

        vr = data.get('vol_rates', {})
        if vr:
            vr_rows = [{'indicator': v['name'], 'value': v['last'],
                        'chg_pct': v['chg_pct'], 'context': v.get('context', '')}
                       for k, v in vr.items() if isinstance(v, dict) and 'last' in v]
            if vr_rows:
                self._sheet_df(wb, "Vol & Rates", pd.DataFrame(vr_rows), ts, ['chg_pct'])

        crypto = data.get('crypto', pd.DataFrame())
        if not (crypto is None or (isinstance(crypto, pd.DataFrame) and crypto.empty)):
            self._sheet_df(wb, "Crypto", crypto, ts, ['chg_1d', 'chg_7d'])

        cal = data.get('calendar', pd.DataFrame())
        if not (cal is None or (isinstance(cal, pd.DataFrame) and cal.empty)):
            self._sheet_df(wb, "Econ Calendar", cal, ts, [])

        # Save to bytes
        buf = io.BytesIO()
        wb.save(buf)
        buf.seek(0)
        return buf.read()

    def export(self, data: dict, filepath: Optional[str] = None) -> str:
        """Save Excel file to disk. Returns the filepath."""
        if filepath is None:
            filepath = f"/tmp/ravinala_macro_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M')}.xlsx"
        xl_bytes = self.export_bytes(data)
        with open(filepath, 'wb') as f:
            f.write(xl_bytes)
        return filepath


# ─────────────────────────────────────────────────────────────────
# EMAIL SENDER
# ─────────────────────────────────────────────────────────────────

class MacroEmailSender:
    """Send Global Macro Snapshot by email via SMTP."""

    def __init__(self, smtp_server: str = "smtp.gmail.com", smtp_port: int = 587,
                 smtp_user: str = "", smtp_password: str = ""):
        self.server   = smtp_server
        self.port     = smtp_port
        self.user     = smtp_user
        self.password = smtp_password

    def build_html_body(self, data: dict) -> str:
        """Build responsive HTML email body."""
        ts  = MacroExcelExporter._utc_timestamp(data.get('timestamp')).strftime('%B %d, %Y — %H:%M UTC')
        idx = data.get('indices', pd.DataFrame())
        fx  = data.get('fx', pd.DataFrame())
        comm= data.get('commodities', pd.DataFrame())
        vr  = data.get('vol_rates', {})
        cal = data.get('calendar', pd.DataFrame())

        def row_html(label, val, chg, fmt=".2f"):
            css = "#00C853" if (chg or 0) >= 0 else "#FF1744"
            sign = "+" if (chg or 0) >= 0 else ""
            return (f'<tr><td style="padding:2px 8px;color:#8B949E;font-size:12px">{label}</td>'
                    f'<td style="padding:2px 8px;color:#E6EDF3;font-size:12px;font-weight:600">'
                    f'{val}</td>'
                    f'<td style="padding:2px 8px;color:{css};font-size:12px">'
                    f'{sign}{chg:{fmt}}%</td></tr>')

        def section(title, rows_html):
            return (f'<div style="margin:12px 0">'
                    f'<div style="color:#00D9A6;font-size:11px;font-weight:700;'
                    f'letter-spacing:.08em;text-transform:uppercase;'
                    f'border-bottom:1px solid #1F2937;padding-bottom:4px;margin-bottom:6px">'
                    f'{title}</div>'
                    f'<table style="width:100%;border-collapse:collapse">{rows_html}</table>'
                    f'</div>')

        # Build sections
        idx_rows = ""
        if not idx.empty:
            for _, r in idx.head(8).iterrows():
                idx_rows += row_html(f'{r.get("flag","")} {r.get("name","")}',
                                     f'{r.get("last",0):,.2f}', r.get('change_pct', 0))

        fx_rows = ""
        if not fx.empty:
            for _, r in fx[fx['group']=='G10'].head(5).iterrows():
                fx_rows += row_html(f'{r.get("flag","")} {r.get("name","")}',
                                    f'{r.get("last",0):.4f}', r.get('change_pct', 0))

        comm_rows = ""
        if not comm.empty:
            for _, r in comm.head(5).iterrows():
                comm_rows += row_html(f'{r.get("flag","")} {r.get("name","")}',
                                      f'{r.get("last",0):,.2f}', r.get('change_pct', 0))

        rates_rows = ""
        for tkr, label in [('^VIX','VIX'), ('^TNX','US 10Y'), ('^TYX','US 30Y'), ('^IRX','US 13W')]:
            d = vr.get(tkr, {}) if vr else {}
            if d.get('last'):
                rates_rows += row_html(label, f'{d["last"]:.3f}%', d.get('chg_pct', 0))

        # Curve
        slope = vr.get('curve_slope') if vr else None
        curve_txt = ""
        if slope is not None:
            inv = "WARNING INVERTED" if slope < 0 else "Normal"
            curve_txt = f'<tr><td style="padding:2px 8px;color:#8B949E;font-size:12px">Curve 10Y–13W</td><td style="padding:2px 8px;color:#E6EDF3;font-size:12px">{slope:+.3f}%</td><td style="font-size:12px;padding:2px 8px">{inv}</td></tr>'
        rates_rows += curve_txt

        cal_rows = ""
        if not cal.empty:
            for _, r in cal[cal['importance'] == 'High'].head(4).iterrows():
                imp_color = "#FF1744"
                cal_rows += (f'<tr><td style="padding:2px 8px;color:#8B949E;font-size:12px">'
                             f'{r.get("flag","")} {r.get("date","")} {r.get("time","")}</td>'
                             f'<td style="padding:2px 8px;color:#E6EDF3;font-size:12px" colspan="2">'
                             f'{r.get("event","")}</td></tr>')

        body = f"""
<!DOCTYPE html>
<html>
<body style="background:#0A0A0F;color:#E6EDF3;font-family:Inter,Arial,sans-serif;margin:0;padding:0">
<table width="600" style="margin:0 auto;background:#111827;border:1px solid #1F2937;border-radius:8px">
  <tr><td style="padding:20px;background:#0D0D20;border-radius:8px 8px 0 0">
    <div style="font-size:20px;font-weight:700;color:#00D9A6"> RAVINALA</div>
    <div style="font-size:13px;color:#8B949E">Global Macro Snapshot</div>
    <div style="font-size:11px;color:#5B7FA6;margin-top:4px">{ts}</div>
  </td></tr>
  <tr><td style="padding:0 20px 20px 20px">
    {section("Equity Indices", idx_rows) if idx_rows else ""}
    {section("Rates & Volatility", rates_rows) if rates_rows else ""}
    {section("FX — G10", fx_rows) if fx_rows else ""}
    {section("Commodities", comm_rows) if comm_rows else ""}
    {section("High-Impact Events", cal_rows) if cal_rows else ""}
    <div style="margin-top:16px;padding-top:12px;border-top:1px solid #1F2937;
                color:#5B7FA6;font-size:10px">
       Full Excel report attached · Generated by Ravinala v2.0 · ravinala.io
    </div>
  </td></tr>
</table>
</body>
</html>
"""
        return body

    def send_snapshot(self, recipient_email: str, data: dict,
                      attach_excel: bool = True,
                      subject: Optional[str] = None) -> bool:
        """Send snapshot email. Returns True on success."""
        if not self.user or not self.password:
            return False
        ts = MacroExcelExporter._utc_timestamp(data.get('timestamp'))
        if subject is None:
            subject = f"Ravinala Macro Snapshot — {ts.strftime('%B %d, %Y %H:%M')} UTC"

        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From']    = self.user
        msg['To']      = recipient_email

        html_body = self.build_html_body(data)
        msg.attach(MIMEText(html_body, 'html'))

        if attach_excel:
            try:
                exporter = MacroExcelExporter()
                xl_bytes = exporter.export_bytes(data)
                part = MIMEBase('application',
                                'vnd.openxmlformats-officedocument.spreadsheetml.sheet')
                part.set_payload(xl_bytes)
                encoders.encode_base64(part)
                fname = f"ravinala_macro_{ts.strftime('%Y%m%d_%H%M')}.xlsx"
                part.add_header('Content-Disposition', 'attachment', filename=fname)
                msg.attach(part)
            except Exception:
                pass  # Send without attachment if Excel fails

        try:
            with smtplib.SMTP(self.server, self.port, timeout=15) as server:
                server.ehlo()
                server.starttls()
                server.login(self.user, self.password)
                server.sendmail(self.user, recipient_email, msg.as_string())
            return True
        except Exception:
            return False
